# Generated by Django 2.1 on 2019-02-13 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.ManyToManyField(null=True, related_name='students', to='dashboard.course'),
        ),
    ]
