# Generated by Django 2.1.7 on 2019-02-14 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20190214_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='idCode',
            field=models.IntegerField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='mobile',
            field=models.IntegerField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.IntegerField(max_length=12, null=True),
        ),
    ]
