# Generated by Django 2.1.7 on 2019-03-31 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookShelf', '0003_remove_book_course'),
        ('dashboard', '0014_auto_20190331_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseinfo',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='bookShelf.book'),
        ),
    ]
