# Generated by Django 2.1.7 on 2019-04-04 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_courseinfo_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='certificate',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
