# Generated by Django 2.1.7 on 2019-03-31 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookShelf', '0002_auto_20190331_2046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='course',
        ),
    ]
