# Generated by Django 2.1.7 on 2019-04-03 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookShelf', '0005_bookgroup_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookgroup',
            name='level',
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='bookgroup',
            name='description',
            field=models.TextField(blank=True, max_length=64, null=True),
        ),
    ]
