# Generated by Django 2.1.7 on 2019-04-03 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookShelf', '0006_auto_20190403_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookgroup',
            name='level',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
