# Generated by Django 2.1 on 2018-09-19 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('course_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='scores', to='dashboard.course')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='score',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='dashboard.score'),
        ),
    ]
