# Generated by Django 2.1 on 2018-11-19 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_remove_course_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='course_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='score',
        ),
        migrations.DeleteModel(
            name='score',
        ),
    ]
