# Generated by Django 2.1 on 2018-11-23 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20181123_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='name',
            field=models.CharField(default=None, max_length=55, null=True),
        ),
    ]
