# Generated by Django 2.1.7 on 2019-02-15 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20190214_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='courseInfo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='dashboard.courseInfo'),
        ),
        migrations.AlterField(
            model_name='score',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='dashboard.course'),
        ),
    ]
