# Generated by Django 2.1 on 2018-11-23 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_remove_score_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='scores', to='dashboard.course'),
        ),
    ]
