# Generated by Django 2.1 on 2018-11-23 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_auto_20181123_1706'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='scorenum',
            new_name='score',
        ),
    ]
