# Generated by Django 2.1.7 on 2019-03-31 20:36

import dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_auto_20190326_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pic',
            field=models.FileField(default='default/profile.png', null=True, upload_to=dashboard.models.picPath),
        ),
    ]
