# Generated by Django 2.1 on 2018-11-23 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_auto_20181123_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='course',
        ),
        migrations.RemoveField(
            model_name='score',
            name='student',
        ),
        migrations.DeleteModel(
            name='score',
        ),
    ]
