# Generated by Django 2.1 on 2018-11-23 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_auto_20181123_1732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='student',
        ),
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.ManyToManyField(null=True, related_name='students', to='dashboard.course'),
        ),
    ]
