# Generated by Django 2.1 on 2018-11-25 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='student',
            field=models.ManyToManyField(null=True, related_name='courses', to='dashboard.student'),
        ),
    ]
