# Generated by Django 2.1 on 2018-11-25 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_course_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='student',
        ),
    ]
