# Generated by Django 2.1 on 2019-02-12 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_remove_course_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='code',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='group',
            field=models.DecimalField(decimal_places=0, max_digits=1, null=True),
        ),
    ]
