# Generated by Django 2.1 on 2019-02-12 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_auto_20190212_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='part',
            field=models.IntegerField(null=True),
        ),
    ]
