# Generated by Django 2.1 on 2019-02-12 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_auto_20190212_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='group',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='scorenum',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='term',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
