# Generated by Django 2.1 on 2019-02-13 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_auto_20190212_1513'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='scorenum',
            new_name='finalScore',
        ),
        migrations.AddField(
            model_name='score',
            name='midScore',
            field=models.FloatField(null=True),
        ),
    ]
