# Generated by Django 2.1 on 2019-02-13 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0027_auto_20190213_1350'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='finalScore',
            new_name='scorenum',
        ),
    ]
