# Generated by Django 2.1 on 2019-02-13 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0028_auto_20190213_1351'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='scorenum',
            new_name='finalScore',
        ),
    ]
