# Generated by Django 2.1.7 on 2019-02-14 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20190213_2346'),
    ]

    operations = [
        migrations.CreateModel(
            name='courseInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=128)),
                ('code', models.CharField(max_length=8, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='code',
        ),
        migrations.RemoveField(
            model_name='course',
            name='course_name',
        ),
        migrations.AddField(
            model_name='course',
            name='courseInfo',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='dashboard.courseInfo'),
        ),
    ]
