# Generated by Django 2.1.7 on 2019-02-14 11:59

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20190214_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=phone_field.models.PhoneField(blank=True, max_length=31, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=phone_field.models.PhoneField(blank=True, max_length=31, null=True),
        ),
    ]
