# Generated by Django 2.1.7 on 2019-03-26 18:03

import dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_user_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pic',
            field=models.FileField(default='settings.MEDIA_ROOT/default/profile.jpg', null=True, upload_to=dashboard.models.picPath),
        ),
    ]
