# Generated by Django 2.1.7 on 2019-04-04 10:50

import dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_teacher_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='pic',
            field=models.FileField(default='default/default teacher.jpg', null=True, upload_to=dashboard.models.teacherPicPath),
        ),
    ]
