# Generated by Django 2.1.7 on 2019-05-09 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_auto_20190509_0837'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='message',
            new_name='massege',
        ),
    ]
