# Generated by Django 2.1.7 on 2019-04-03 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookShelf', '0004_auto_20190401_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookgroup',
            name='description',
            field=models.TextField(blank=True, max_length=512, null=True),
        ),
    ]
