# Generated by Django 2.1.7 on 2019-05-13 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookShelf', '0012_auto_20190513_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bookShelf.BookGroup'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publish_date',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='bookShelf.Date'),
        ),
    ]
