# Generated by Django 2.1.7 on 2019-05-13 15:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='dashboard.CourseInfo'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='checkout_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2019, 5, 13, 15, 4, 40, 681586)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='receipt',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipt', to='dashboard.CourseInfo'),
        ),
    ]
