# Generated by Django 2.1.7 on 2019-05-13 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_auto_20190513_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='dashboard.CourseInfo'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipt', to='dashboard.CourseInfo'),
        ),
    ]
