# Generated by Django 2.1.7 on 2019-03-31 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookShelf', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True, max_length=512, null=True),
        ),
    ]
